<div class="container">
    <!-- Navigation des catégories et salons -->
    <aside>
        <div>
            <h3>Mon espace</h3>
            <ul class='category-list'>
                <?php if(isset($_SESSION['logged']) && $_SESSION['logged']): ?>
                    <li><a href="index.php?page=profile" class='main-link'>Mon profil</a></li>
                    <li><a href="index.php?page=profile&action=settings" class='main-link'>Paramètres</a></li>
                    <li><a href="index.php?page=profile&action=logout" class='main-link delete-btn'>Se déconnecter</a></li>
                <?php else: ?>
                    <li><a href="index.php?page=profile">Se connecter</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </aside>

    <div class='main'>
        
        <?php require $sub_template ?>
        
    </div>
</div>