<h3>Mon profil</h3>

<?php if($action === 'edit-user'): ?>

    <form method="post" class='bigForm signUp'>

        <label for="firstname">Prénom :</label>
        <input type="text" name="firstname" id="firstname" maxlength="100" value='<?= htmlspecialchars($_SESSION['user']['firstname']); ?>' required>
        <?php if (!empty($errors['firstname'])): ?>
            <div class="error"><?= htmlspecialchars($errors['firstname']) ?></div>
        <?php endif; ?>
    
        <label for="lastname">Nom :</label>
        <input type="text" name="lastname" id="lastname" maxlength="100" value='<?= htmlspecialchars($_SESSION['user']['lastname']); ?>' required>
        <?php if (!empty($errors['lastname'])): ?>
            <div class="error"><?= htmlspecialchars($errors['lastname']) ?></div>
        <?php endif; ?>
        
        <label for="pseudo">Pseudo :</label>
        <input type="text" name="pseudo" id="pseudo" maxlength="50" value='<?= htmlspecialchars($_SESSION['user']['pseudo']); ?>' required>
        <?php if (!empty($errors['pseudo'])): ?>
            <div class="error"><?= htmlspecialchars($errors['pseudo']) ?></div>
        <?php endif; ?>
        
        <label for="email">Email :</label>
        <input type="email" name="email" id="email" maxlength="255" value='<?= htmlspecialchars($_SESSION['user']['email']); ?>' required>
        <?php if (!empty($errors['email'])): ?>
            <div class="error"><?= htmlspecialchars($errors['email']) ?></div>
        <?php endif; ?>
        
        <label for="tel">Téléphone :</label>
        <input type="tel" name="tel" id="tel" maxlength="10" pattern="\d{10}" value='<?= htmlspecialchars($_SESSION['user']['tel']); ?>' required>
        <?php if (!empty($errors['tel'])): ?>
            <div class="error"><?= htmlspecialchars($errors['tel']) ?></div>
        <?php endif; ?>
    
        <label for="birthdate">Date de naissance :</label>
        <input type="date" name="birthdate" id="birthdate" value='<?= htmlspecialchars($_SESSION['user']['birthdate']->format('Y-m-d')); ?>' required>
        <?php if (!empty($errors['birthdate'])): ?>
            <div class="error"><?= htmlspecialchars($errors['birthdate']) ?></div>
        <?php endif; ?>
    
        <label for="address-number">Numéro de rue :</label>
        <input type="number" name="address-number" id="address-number" value='<?= htmlspecialchars($_SESSION['user']['address_number']); ?>'>
        <?php if (!empty($errors['address-number'])): ?>
            <div class="error"><?= htmlspecialchars($errors['address-number']) ?></div>
        <?php endif; ?>
    
        <label for="address-street">Nom de rue :</label>
        <input type="text" name="address-street" id="address-street" value='<?= htmlspecialchars($_SESSION['user']['address_street']); ?>' maxlength="255" required>
        <?php if (!empty($errors['address-street'])): ?>
            <div class="error"><?= htmlspecialchars($errors['address-street']) ?></div>
        <?php endif; ?>
    
        <label for="address-city">Ville :</label>
        <input type="text" name="address-city" id="address-city" value='<?= htmlspecialchars($_SESSION['user']['address_city']); ?>' maxlength="255" required>
        <?php if (!empty($errors['address-city'])): ?>
            <div class="error"><?= htmlspecialchars($errors['address-city']) ?></div>
        <?php endif; ?>
    
        <label for="address-postal-code">Code postal :</label>
        <input type="text" name="address-postal-code" id="address-postal-code" value='<?= htmlspecialchars($_SESSION['user']['address_postal_code']); ?>' maxlength="5" pattern="\d{5}" required>
        <?php if (!empty($errors['address-postal-code'])): ?>
            <div class="error"><?= htmlspecialchars($errors['address-postal-code']) ?></div>
        <?php endif; ?>
    
        <label for="address-country">Pays :</label>
        <input type="text" name="address-country" id="address-country" value='<?= htmlspecialchars($_SESSION['user']['address_country']); ?>' maxlength="255" required>
        <?php if (!empty($errors['address-country'])): ?>
            <div class="error"><?= htmlspecialchars($errors['address-country']) ?></div>
        <?php endif; ?>
    
        <button type="submit" name='submit'>Modifier</button>
    </form>

<?php else: ?>

    <div class="profile-info">
        <ul class='info-list'>
            <li><strong>Prénom :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['firstname']); ?></li>
            <li><strong>Nom :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['lastname']); ?></li>
            <li><strong>Pseudo :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['pseudo']); ?></li>
            <li><strong>Email :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['email']); ?></li>
            <li><strong>Télephone :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['tel']); ?></li>
            <li><strong>Date de naissance :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['birthdate']->format('d/m/Y')); ?></li>
            <li><strong>Adresse :</strong></li>
            <li><?= htmlspecialchars($_SESSION['user']['address_number']) . ' ' . htmlspecialchars($_SESSION['user']['address_street']) . ' - ' . htmlspecialchars($_SESSION['user']['address_city']) . ' - ' . htmlspecialchars($_SESSION['user']['address_postal_code']) . ' - ' . htmlspecialchars($_SESSION['user']['address_country']); ?></li>
        </ul>
        <a href='index.php?page=profile&action=edit-user' class='button'>Modifier mes informations</a>
    </div>
    
<?php endif; ?>