<!doctype html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Distorsion | Echangez simplement">
    <title>Distorsion | Echangez simplement</title>
    <link rel="icon" type="image/png" href="./public/assets/img/logo.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="./public/assets/css/style.css" type="text/css">
</head>

<body>
    <header>
        <nav>
            <div class='logo'>
                <h1><strong>Distorsion</strong></h1>
                <a href="index.php">
                    <img src='./public/assets/img/logo.png' alt='Logo Distorsion'>
                </a>
            </div>
            <ul class='nav-links'>
                <li><a href="index.php?page=home">Chat</a></li>
                <li class='profile-menu'>
                    <a href="index.php?page=profile">Mon espace</a>
                    <ul class="dropdown">
                        <?php if(isset($_SESSION['logged']) && $_SESSION['logged']): ?> 
                            <li><a href="index.php?page=profile">Mon profil</a></li>
                            <li><a href="index.php?page=profile&action=settings">Paramètres</a></li>
                            <li><a href="index.php?page=profile&action=logout" class='delete-btn'>Se déconnecter</a></li>
                        <?php else: ?>
                            <li><a href="index.php?page=profile">Se connecter</a></li>
                        <?php endif; ?>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    
    <main>
        <?php require $template ?>
    </main>
    
    <div id="custom-confirm-popup" class="popup">
        <div class="popup-content">
            <h2>En êtes-vous sûr ?</h2>
            <p>Cette action est irréversible.</p>
            <div class="popup-actions">
                <button class='delete' id="confirm">Oui, continuer</button>
                <button id="cancel">Annuler</button>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="./public/js/main.js"></script>
    
</body>
</html>